spring:
  application:
    name: microservice-comsumer-student
server:
  port: 9050
student: 
  studentServicePath: http://microservice-provider-student/student/

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true